services:
  app:
    build: 
      context: ..
      dockerfile: docker/Dockerfile.dev.be
    volumes:
      - ../backend/src:/app/src
      - ../backend/alembic:/app/alembic
      - ../backend/public:/app/public
    env_file:
      - ../.env
    ports:
      - "5002:5001"
    depends_on:
      db_service:
        condition: service_healthy
      redis-broker:
        condition: service_healthy

  celery-worker:
    build: 
      context: ..
      dockerfile: docker/Dockerfile.dev.be
    volumes:
      - ../backend/src:/app/src
    env_file:
      - ../.env
    depends_on:
      db_service:
        condition: service_healthy
      redis-broker:
        condition: service_healthy
    command: >
      celery -A src.celery_worker.worker.celery_app worker --loglevel=info

  db_service:
    image: postgres:16
    env_file:
      - ../.env
    ports:
      - "5422:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init.sh
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 3

  redis-broker:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./redis_data:/data
    restart: always

volumes:
  postgres_data:
  redis_data:
