services:
  app:
    build: 
      context: ..
      dockerfile: docker/Dockerfile.dev.be
    volumes:
      - ../backend/src:/app/src
      - ../backend/alembic:/app/alembic
      - ../backend/public:/app/public
    env_file:
      - ../.env
    ports:
      - "5002:5001"
    depends_on:
      db_service:
        condition: service_healthy
      redis-service:
        condition: service_healthy
    # restart: always

  celery-worker:
    build: 
      context: ..
      dockerfile: docker/Dockerfile.dev.be
    volumes:
      - ../backend/src:/app/src
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD-SHELL", "celery -A src.celery_worker.celery_worker.celery_app inspect ping -d celery@$$HOSTNAME | grep -q 'pong'"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db_service:
        condition: service_healthy
      redis-service:
        condition: service_healthy
    command: >
      sh -c "
        watchfiles 'celery -A src.celery_worker.celery_worker.celery_app worker --loglevel=info' /app/src
      "
    # restart: always

  # flower:
  #   image: mher/flower:master
  #   env_file:
  #     - ../.env
  #   command: >
  #     celery
  #     --broker=${CELERY_BROKER_URL}
  #     flower
  #     --port=5555
  #   ports:
  #     - "5555:5555"
  #   depends_on:
  #     redis-service:
  #       condition: service_healthy
  #     celery-worker:
  #       condition: service_healthy
    # Add this to command (if needed) to enable basic auth
    # --basic_auth=admin:secret

  db_service:
    image: postgres:16
    env_file:
      - ../.env
    ports:
      - "5422:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init.sh
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 3

  redis-service:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./redis_data:/data
    restart: always

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      redis-service:
        condition: service_healthy
    volumes:
      - ./redisinsight_data:/db

volumes:
  postgres_data:
  redis_data:
